#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from rclpy.executors import MultiThreadedExecutor
from pic4rl.tasks.goToPose.pic4rl_lidar import Pic4rlLidar

import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices('GPU')

if gpus:
    try:
    # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
            logical_gpus = tf.config.experimental.list_logical_devices('GPU')
            # print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
        print(e)

def main(args=None):
    rclpy.init(args=args)

    pic4rl_lidar = Pic4rlLidar()

    # executor = MultiThreadedExecutor()
    # executor.add_node(pic4rl_lidar)

    try:
        # executor.spin()
        pic4rl_lidar.threadFunc()
    except KeyboardInterrupt:
        # executor.shutdown()
        pic4rl_lidar.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
