#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from rclpy.executors import SingleThreadedExecutor
from pic4rl.tasks.goToPose.pic4rl_camera import Pic4rlCamera

def main(args=None):
    rclpy.init(args=args)

    pic4rl_camera = Pic4rlCamera()

    executor = SingleThreadedExecutor()
    executor.add_node(pic4rl_camera)

    if pic4rl_camera.tflite_flag:
        executor.spin(pic4rl_camera.threadFunc_tflite)
    else:
        executor.spin(pic4rl_camera.threadFunc)

    rclpy.shutdown()

if __name__ == "__main__":
    main()

